name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -tags netgo -ldflags '-s -w' -o app

    - name: Test
      run: go test -v
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Push
      uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "quiet-brook-87537"
        heroku_email: "lucaoxita@gmail.com"
        usedocker: true
      env:
          NODE_ENV: production
          STREAMING_URL: ${{ secrets.STREAMING_URL }}
